sudo: false
bundler_args: --without development
before_install: gem install bundler
cache: bundler
language: ruby
script:
  - bundle exec rake
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby
allow_failure:
  - rvm: ruby-head